name: Build

on:
  push:
    branches:
      - main  # Change this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          touch ~/.aws/credentials.pem
          echo "${{ secrets.AWS_PEM_FILE }}" > ~/.aws/credentials.pem
          chmod 600 ~/.aws/credentials.pem

      - name: Run deployment script
        run: bash deploy.sh
